/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HandoffRouteImport } from './routes/handoff'
import { Route as PatronRouteImport } from './routes/patron'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SecretRouteImport } from './routes/secret'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffRoute = HandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const PatronRoute = PatronRouteImport.update({
  id: '/patron',
  path: '/patron',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretRoute = SecretRouteImport.update({
  id: '/secret',
  path: '/secret',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/handoff': typeof HandoffRoute
  '/patron': typeof PatronRoute
  '/review': typeof ReviewRoute
  '/secret': typeof SecretRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/handoff': typeof HandoffRoute
  '/patron': typeof PatronRoute
  '/review': typeof ReviewRoute
  '/secret': typeof SecretRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/handoff': typeof HandoffRoute
  '/patron': typeof PatronRoute
  '/review': typeof ReviewRoute
  '/secret': typeof SecretRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/handoff' | '/patron' | '/review' | '/secret'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/handoff' | '/patron' | '/review' | '/secret'
  id: '__root__' | '/' | '/handoff' | '/patron' | '/review' | '/secret'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandoffRoute: typeof HandoffRoute
  PatronRoute: typeof PatronRoute
  ReviewRoute: typeof ReviewRoute
  SecretRoute: typeof SecretRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff': {
      id: '/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof HandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patron': {
      id: '/patron'
      path: '/patron'
      fullPath: '/patron'
      preLoaderRoute: typeof PatronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret': {
      id: '/secret'
      path: '/secret'
      fullPath: '/secret'
      preLoaderRoute: typeof SecretRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandoffRoute: HandoffRoute,
  PatronRoute: PatronRoute,
  ReviewRoute: ReviewRoute,
  SecretRoute: SecretRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
